[tool.black]
line-length = 88
skip-string-normalization = false
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
plugins = [
  "pydantic.mypy"
]

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
