name: "CodeReviewAssistant-BugFixer"

on:
  pull_request:
  workflow_dispatch:

jobs:
  bug-fixer:
    name: "Bug Fixer"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Checkout CodeReviewAssistant-BugFixer"
        uses: "actions/checkout@v2"
        with:
          repository: "OSFDigital/CodeReviewAssistant-BugFixer"
          ref: "main"
          ssh-key: "${{ secrets.CODE_REVIEW_ASSISTANT_BUG_FIXER_SSH_KEY }}"
          path: ".github/actions/CodeReviewAssistant-BugFixer"

      - name: "Run CodeReviewAssistant-BugFixer"
        uses: "./.github/actions/CodeReviewAssistant-BugFixer"
        with:
          openai_key: "${{ secrets.CODE_REVIEW_ASSISTANT_BUG_FIXER_OPENAI_KEY }}"
          openai_org: "${{ secrets.CODE_REVIEW_ASSISTANT_BUG_FIXER_OPENAI_ORG }}"
          app_id: "${{ secrets.CODE_REVIEW_ASSISTANT_BUG_FIXER_GITHUB_APP_ID }}"
          private_pem: "${{ secrets.CODE_REVIEW_ASSISTANT_BUG_FIXER_GITHUB_PRIVATE_KEY }}"
          client_id: "${{ secrets.CODE_REVIEW_ASSISTANT_BUG_FIXER_GITHUB_CLIENT_ID }}"
          client_secret: "${{ secrets.CODE_REVIEW_ASSISTANT_BUG_FIXER_GITHUB_CLIENT_SECRET }}"
