# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy package to PyPI.

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish to PyPI.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Build package.
        working-directory: ./redb/
        run: |
          python -m pip install --upgrade pip build
          python -m build .
      - name: Publish.
        uses: pypa/gh-action-pypi-publish@v1.6.4
        working-directory: ./redb/
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          print_hash: true
