name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
  MONGO_URI: ${{ secrets.TEST_MONGO_SECRET }}

jobs:
  autotester:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: |
            redb/requirements-*.txt
      - name: Setup pip and pytest
        working-directory: ./redb/
        run: |
          python -m pip install --upgrade pip
          pip install ./
      - name: Install and test `redb`.
        working-directory: ./redb/
        run: |
          pip install -r requirements-test.txt
          pytest ./tests/ --tb=no
